/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> } 
 */
exports.seed = async function(knex) {
  // Deletes ALL existing entries
  await knex('clients').del()
  await knex('clients').insert([
    {
        "client_id": 1,
        "client_name": "Homer",
        "client_lastname": "Simpson",
        "client_email": "homer.simpson@example.com",
        "client_phone": "123-456-7890",
        "client_addr_street": "742 Evergreen Terrace",
        "client_addr_zipcode": "12345",
        "client_addr_barrio": "Springfield",
        "client_addr_city": "Springfield",
        "active": true
    },
    {
        "client_id": 2,
        "client_name": "Marge",
        "client_lastname": "Simpson",
        "client_email": "marge.simpson@example.com",
        "client_phone": "123-456-7891",
        "client_addr_street": "742 Evergreen Terrace",
        "client_addr_zipcode": "12345",
        "client_addr_barrio": "Springfield",
        "client_addr_city": "Springfield",
        "active": true
    },
    {
        "client_id": 3,
        "client_name": "Bart",
        "client_lastname": "Simpson",
        "client_email": "bart.simpson@example.com",
        "client_phone": "123-456-7892",
        "client_addr_street": "742 Evergreen Terrace",
        "client_addr_zipcode": "12345",
        "client_addr_barrio": "Springfield",
        "client_addr_city": "Springfield",
        "active": true
    },
    {
        "client_id": 4,
        "client_name": "Lisa",
        "client_lastname": "Simpson",
        "client_email": "lisa.simpson@example.com",
        "client_phone": "123-456-7893",
        "client_addr_street": "742 Evergreen Terrace",
        "client_addr_zipcode": "12345",
        "client_addr_barrio": "Springfield",
        "client_addr_city": "Springfield",
        "active": true
    },
    {
        "client_id": 5,
        "client_name": "Maggie",
        "client_lastname": "Simpson",
        "client_email": "maggie.simpson@example.com",
        "client_phone": "123-456-7894",
        "client_addr_street": "742 Evergreen Terrace",
        "client_addr_zipcode": "12345",
        "client_addr_barrio": "Springfield",
        "client_addr_city": "Springfield",
        "active": true
    },
    {
        "client_id": 6,
        "client_name": "Ned",
        "client_lastname": "Flanders",
        "client_email": "ned.flanders@example.com",
        "client_phone": "123-456-7895",
        "client_addr_street": "744 Evergreen Terrace",
        "client_addr_zipcode": "12345",
        "client_addr_barrio": "Springfield",
        "client_addr_city": "Springfield",
        "active": true
    },
    {
        "client_id": 7,
        "client_name": "Maude",
        "client_lastname": "Flanders",
        "client_email": "maude.flanders@example.com",
        "client_phone": "123-456-7896",
        "client_addr_street": "744 Evergreen Terrace",
        "client_addr_zipcode": "12345",
        "client_addr_barrio": "Springfield",
        "client_addr_city": "Springfield",
        "active": true
    },
    {
        "client_id": 8,
        "client_name": "Rod",
        "client_lastname": "Flanders",
        "client_email": "rod.flanders@example.com",
        "client_phone": "123-456-7897",
        "client_addr_street": "744 Evergreen Terrace",
        "client_addr_zipcode": "12345",
        "client_addr_barrio": "Springfield",
        "client_addr_city": "Springfield",
        "active": true
    },
    {
        "client_id": 9,
        "client_name": "Todd",
        "client_lastname": "Flanders",
        "client_email": "todd.flanders@example.com",
        "client_phone": "123-456-7898",
        "client_addr_street": "744 Evergreen Terrace",
        "client_addr_zipcode": "12345",
        "client_addr_barrio": "Springfield",
        "client_addr_city": "Springfield",
        "active": true
    },
    {
        "client_id": 10,
        "client_name": "Montgomery",
        "client_lastname": "Burns",
        "client_email": "montgomery.burns@example.com",
        "client_phone": "123-456-7899",
        "client_addr_street": "Montgomery Burns Manor",
        "client_addr_zipcode": "12345",
        "client_addr_barrio": "Springfield",
        "client_addr_city": "Springfield",
        "active": true
    },
    {
        "client_id": 11,
        "client_name": "Waylon",
        "client_lastname": "Smithers",
        "client_email": "waylon.smithers@example.com",
        "client_phone": "123-456-7810",
        "client_addr_street": "123 Smithers Lane",
        "client_addr_zipcode": "12345",
        "client_addr_barrio": "Springfield",
        "client_addr_city": "Springfield",
        "active": true
    },
    {
        "client_id": 12,
        "client_name": "Moe",
        "client_lastname": "Szyslak",
        "client_email": "moe.szyslak@example.com",
        "client_phone": "123-456-7811",
        "client_addr_street": "123 Moe's Tavern",
        "client_addr_zipcode": "12345",
        "client_addr_barrio": "Springfield",
        "client_addr_city": "Springfield",
        "active": true
    },
    {
        "client_id": 13,
        "client_name": "Apu",
        "client_lastname": "Nahasapeemapetilon",
        "client_email": "apu.nahasapeemapetilon@example.com",
        "client_phone": "123-456-7812",
        "client_addr_street": "456 Kwik-E-Mart",
        "client_addr_zipcode": "12345",
        "client_addr_barrio": "Springfield",
        "client_addr_city": "Springfield",
        "active": true
    },
    {
        "client_id": 14,
        "client_name": "Barney",
        "client_lastname": "Gumble",
        "client_email": "barney.gumble@example.com",
        "client_phone": "123-456-7813",
        "client_addr_street": "123 Moe's Tavern",
        "client_addr_zipcode": "12345",
        "client_addr_barrio": "Springfield",
        "client_addr_city": "Springfield",
        "active": true
    },
    {
        "client_id": 15,
        "client_name": "Seymour",
        "client_lastname": "Skinner",
        "client_email": "seymour.skinner@example.com",
        "client_phone": "123-456-7814",
        "client_addr_street": "123 Springfield Elementary",
        "client_addr_zipcode": "12345",
        "client_addr_barrio": "Springfield",
        "client_addr_city": "Springfield",
        "active": true
    },
    {
        "client_id": 16,
        "client_name": "Edna",
        "client_lastname": "Krabappel",
        "client_email": "edna.krabappel@example.com",
        "client_phone": "123-456-7815",
        "client_addr_street": "123 Springfield Elementary",
        "client_addr_zipcode": "12345",
        "client_addr_barrio": "Springfield",
        "client_addr_city": "Springfield",
        "active": true
    },
    {
        "client_id": 17,
        "client_name": "Groundskeeper",
        "client_lastname": "Willie",
        "client_email": "groundskeeper.willie@example.com",
        "client_phone": "123-456-7816",
        "client_addr_street": "123 Springfield Elementary",
        "client_addr_zipcode": "12345",
        "client_addr_barrio": "Springfield",
        "client_addr_city": "Springfield",
        "active": true
    },
    {
        "client_id": 18,
        "client_name": "Patty",
        "client_lastname": "Bouvier",
        "client_email": "patty.bouvier@example.com",
        "client_phone": "123-456-7817",
        "client_addr_street": "123 Main Street",
        "client_addr_zipcode": "12345",
        "client_addr_barrio": "Springfield",
        "client_addr_city": "Springfield",
        "active": true
    },
    {
        "client_id": 19,
        "client_name": "Selma",
        "client_lastname": "Bouvier",
        "client_email": "selma.bouvier@example.com",
        "client_phone": "123-456-7818",
        "client_addr_street": "123 Main Street",
        "client_addr_zipcode": "12345",
        "client_addr_barrio": "Springfield",
        "client_addr_city": "Springfield",
        "active": true
    },
    {
        "client_id": 20,
        "client_name": "Cletus",
        "client_lastname": "Spuckler",
        "client_email": "cletus.spuckler@example.com",
        "client_phone": "123-456-7819",
        "client_addr_street": "742 Evergreen Terrace",
        "client_addr_zipcode": "12345",
        "client_addr_barrio": "Springfield",
        "client_addr_city": "Springfield",
        "active": true
    },
    {
        "client_id": 21,
        "client_name": "Lenny",
        "client_lastname": "Leonard",
        "client_email": "lenny.leonard@example.com",
        "client_phone": "123-456-7820",
        "client_addr_street": "123 Main Street",
        "client_addr_zipcode": "12345",
        "client_addr_barrio": "Springfield",
        "client_addr_city": "Springfield",
        "active": true
    },
    {
        "client_id": 22,
        "client_name": "Carl",
        "client_lastname": "Carlson",
        "client_email": "carl.carlson@example.com",
        "client_phone": "123-456-7821",
        "client_addr_street": "123 Main Street",
        "client_addr_zipcode": "12345",
        "client_addr_barrio": "Springfield",
        "client_addr_city": "Springfield",
        "active": true
    },
    {
        "client_id": 23,
        "client_name": "Chief",
        "client_lastname": "Wiggum",
        "client_email": "chief.wiggum@example.com",
        "client_phone": "123-456-7822",
        "client_addr_street": "123 Main Street",
        "client_addr_zipcode": "12345",
        "client_addr_barrio": "Springfield",
        "client_addr_city": "Springfield",
        "active": true
    },
    {
        "client_id": 24,
        "client_name": "Ralph",
        "client_lastname": "Wiggum",
        "client_email": "ralph.wiggum@example.com",
        "client_phone": "123-456-7823",
        "client_addr_street": "123 Main Street",
        "client_addr_zipcode": "12345",
        "client_addr_barrio": "Springfield",
        "client_addr_city": "Springfield",
        "active": true
    },
    {
        "client_id": 25,
        "client_name": "Krusty",
        "client_lastname": "the Clown",
        "client_email": "krusty.clown@example.com",
        "client_phone": "123-456-7824",
        "client_addr_street": "123 Krusty Studios",
        "client_addr_zipcode": "12345",
        "client_addr_barrio": "Springfield",
        "client_addr_city": "Springfield",
        "active": true
    },
    {
        "client_id": 26,
        "client_name": "Sideshow",
        "client_lastname": "Bob",
        "client_email": "sideshow.bob@example.com",
        "client_phone": "123-456-7825",
        "client_addr_street": "123 Springfield Penitentiary",
        "client_addr_zipcode": "12345",
        "client_addr_barrio": "Springfield",
        "client_addr_city": "Springfield",
        "active": true
    },
    {
        "client_id": 27,
        "client_name": "Patty",
        "client_lastname": "Selma",
        "client_email": "patty.selma@example.com",
        "client_phone": "123-456-7826",
        "client_addr_street": "123 Main Street",
        "client_addr_zipcode": "12345",
        "client_addr_barrio": "Springfield",
        "client_addr_city": "Springfield",
        "active": true
    },
    {
        "client_id": 28,
        "client_name": "Rainier",
        "client_lastname": "Wolfcastle",
        "client_email": "rainier.wolfcastle@example.com",
        "client_phone": "123-456-7827",
        "client_addr_street": "123 Wolfcastle Mansion",
        "client_addr_zipcode": "12345",
        "client_addr_barrio": "Springfield",
        "client_addr_city": "Springfield",
        "active": true
    },
    {
        "client_id": 29,
        "client_name": "Lionel",
        "client_lastname": "Hutz",
        "client_email": "lionel.hutz@example.com",
        "client_phone": "123-456-7828",
        "client_addr_street": "123 Wolfcastle",
        "client_addr_zipcode": "12345",
        "client_addr_barrio": "Springfield",
        "client_addr_city": "Springfield",
        "active": true
    }      
  ]);
};
